### ISSUE TITLE
Vanced YouTube is dead

### ISSUE THREAD

**Issue by Amby713** [Shakil-Shahadat/awesome-piracy#11]
YouTube vanced is discontinued due to cease and desist from Google.

Revanced.app or  https://github.com/revanced/revanced-manager/ is the next best bet

Also libretube (https://github.com/libre-tube/LibreTube )

**Comment by Shakil-Shahadat** [comment]
Yes, the original vanced is dead. But can you tell if the version provided by https://youtubevanced.com/ or https://www.vanced-official.com/ are trustworthy? I have been using the manager from https://youtubevanced.com/ for the last few days and everything seems alright. But the SHA-256 provided by https://vancedapp.com/ doesn't match with the manager.apk.

The official [subreddit](https://www.reddit.com/r/Vanced/) says, the app is still working and will probably work for 2-3 more years. So, I'm thinking of adding a download link instead of removing it completely.

Also, Revanced manager is in the alpha stage at this moment. Does that mean, Revanced is also in the alpha version? Does it support all the features of Vanced?
